spring:
  application:
    name: store-api
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate.show_sql: true
      use_sql_comments: true
      format_sql: true
  flyway:
    enabled: true
    check-location: true
    locations: classpath:db/migration
    schemas: cox
    table: schema_version



server:
  port: 8081
  servlet:
    context-path: /store-api


cox:
  store:
    data:
      spring:
        datasource:
          url: jdbc:mysql://localhost:3308/cox?autoReconnect=true&useSSL=false&serverTimezone=UTC
          port: 3308
          username: cox
          password: my-secret-pw
          schema: cox
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
      hibernate:
        show_sql: false
